# Site settings
title: K.E.I.T.H. The Robot
email: harrymerckel@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A blog about K.E.I.T.H., a Raspberry Pi powered robot made by Harry and Andy Merckel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://keiththerobot.uk" # the base hostname & protocol for your site
twitter_username: davedude0
github_username:  davedude0

highlighter: pygments
encoding: utf-8

# Build settings
markdown: kramdown
