# Site settings
title: KEITH
tagline: Home
email: blog@keiththerobot.uk
description: > # this means to ignore newlines until "baseurl:"
  KEITH (Kinetic Electronic Interactive Tracked Hardware), a Raspberry Pi powered robot programmed and made by Harry and Andy Merckel.
baseurl: "/" # the subpath of your site, e.g. /blog/
evourl: "/KEITH-Evo/"
url: "http://keiththerobot.uk" # the base hostname & protocol for your site
twitter_username: KEITHtheRobot
github_username:  davedude0

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /post/:title
relative_permalinks: true

paginate:         5
paginate_path:    /KEITH-Evo/page:num

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/davedude0/
