# Site settings
title: K路E路I路T路H
tagline: Home
email: harrymerckel@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  KEITH, a Raspberry Pi powered robot programmed and made by Harry and Andy Merckel.
  Kinetic Electronic Interactive Tracked Hardware.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://keiththerobot.uk" # the base hostname & protocol for your site
twitter_username: davedude0
github_username:  davedude0

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/davedude0/
