# Site settings
title: K.E.I.T.H.
tagline: Home
email: harrymerckel@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A blog about K.E.I.T.H., a Raspberry Pi powered robot made by Harry and Andy Merckel.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://keiththerobot.uk" # the base hostname & protocol for your site
twitter_username: davedude0
github_username:  davedude0

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/davedude0/
