# Site settings
title: KEITH
tagline: Blog for KEITH, a series Raspberry Pi powered robots for PiWars
email: blog@keiththerobot.uk
description: > # this means to ignore newlines until "baseurl:" allowing a multiline description
  KEITH (Kinetic Electronic Interactive Tracked Hardware), a series of Raspberry Pi powered robots programmed and made by Harry and Andy Merckel.
baseurl: "/" # the subpath of your site, e.g. /blog/
blogurl: "/blog/"
url: "http://keiththerobot.uk" # the base hostname & protocol for your site
twitter_username: KEITHtheRobot
github_username:  davedude0

# Dependencies
markdown:         kramdown
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-paginate

# Permalinks
permalink:        /post/:title

#paginate:         5
#paginate_path:    /blog/page:num
#paginate_category: "K2017"

# Custom vars

github:
  repo:           https://github.com/HarryMerckel/
